// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/ggorder_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GGOrderUpdateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customerName,proto3" json:"customerName,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GGOrderUpdateModel) Reset() {
	*x = GGOrderUpdateModel{}
	mi := &file_models_ggorder_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GGOrderUpdateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GGOrderUpdateModel) ProtoMessage() {}

func (x *GGOrderUpdateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_ggorder_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GGOrderUpdateModel.ProtoReflect.Descriptor instead.
func (*GGOrderUpdateModel) Descriptor() ([]byte, []int) {
	return file_models_ggorder_model_proto_rawDescGZIP(), []int{0}
}

func (x *GGOrderUpdateModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GGOrderUpdateModel) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *GGOrderUpdateModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GGOrderUpdateModel) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_models_ggorder_model_proto protoreflect.FileDescriptor

const file_models_ggorder_model_proto_rawDesc = "" +
	"\n" +
	"\x1amodels/ggorder_model.proto\x12\x11ggorder.models.v1\"x\n" +
	"\x12GGOrderUpdateModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\"\n" +
	"\fcustomerName\x18\x02 \x01(\tR\fcustomerName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetailsB=Z;github.com/timur-chilli/ggshop/warehouse/internal/pb/modelsb\x06proto3"

var (
	file_models_ggorder_model_proto_rawDescOnce sync.Once
	file_models_ggorder_model_proto_rawDescData []byte
)

func file_models_ggorder_model_proto_rawDescGZIP() []byte {
	file_models_ggorder_model_proto_rawDescOnce.Do(func() {
		file_models_ggorder_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_ggorder_model_proto_rawDesc), len(file_models_ggorder_model_proto_rawDesc)))
	})
	return file_models_ggorder_model_proto_rawDescData
}

var file_models_ggorder_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_ggorder_model_proto_goTypes = []any{
	(*GGOrderUpdateModel)(nil), // 0: ggorder.models.v1.GGOrderUpdateModel
}
var file_models_ggorder_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_ggorder_model_proto_init() }
func file_models_ggorder_model_proto_init() {
	if File_models_ggorder_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_ggorder_model_proto_rawDesc), len(file_models_ggorder_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_ggorder_model_proto_goTypes,
		DependencyIndexes: file_models_ggorder_model_proto_depIdxs,
		MessageInfos:      file_models_ggorder_model_proto_msgTypes,
	}.Build()
	File_models_ggorder_model_proto = out.File
	file_models_ggorder_model_proto_goTypes = nil
	file_models_ggorder_model_proto_depIdxs = nil
}
