// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/timur-chilli/ggshop/customer_side/internal/models"
)

// NewMockGGOrderStorage creates a new instance of MockGGOrderStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGGOrderStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGGOrderStorage {
	mock := &MockGGOrderStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGGOrderStorage is an autogenerated mock type for the GGOrderStorage type
type MockGGOrderStorage struct {
	mock.Mock
}

type MockGGOrderStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGGOrderStorage) EXPECT() *MockGGOrderStorage_Expecter {
	return &MockGGOrderStorage_Expecter{mock: &_m.Mock}
}

// GetGGOrderInfoByIDs provides a mock function for the type MockGGOrderStorage
func (_mock *MockGGOrderStorage) GetGGOrderInfoByIDs(ctx context.Context, IDs []uint64) ([]*models.GGOrderInfo, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetGGOrderInfoByIDs")
	}

	var r0 []*models.GGOrderInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.GGOrderInfo, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) []*models.GGOrderInfo); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GGOrderInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGGOrderStorage_GetGGOrderInfoByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGGOrderInfoByIDs'
type MockGGOrderStorage_GetGGOrderInfoByIDs_Call struct {
	*mock.Call
}

// GetGGOrderInfoByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockGGOrderStorage_Expecter) GetGGOrderInfoByIDs(ctx interface{}, IDs interface{}) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	return &MockGGOrderStorage_GetGGOrderInfoByIDs_Call{Call: _e.mock.On("GetGGOrderInfoByIDs", ctx, IDs)}
}

func (_c *MockGGOrderStorage_GetGGOrderInfoByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint64
		if args[1] != nil {
			arg1 = args[1].([]uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGGOrderStorage_GetGGOrderInfoByIDs_Call) Return(gGOrderInfos []*models.GGOrderInfo, err error) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	_c.Call.Return(gGOrderInfos, err)
	return _c
}

func (_c *MockGGOrderStorage_GetGGOrderInfoByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uint64) ([]*models.GGOrderInfo, error)) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertGGOrderInfo provides a mock function for the type MockGGOrderStorage
func (_mock *MockGGOrderStorage) InsertGGOrderInfo(ctx context.Context, GGOrderInfos []*models.GGOrderInfo) error {
	ret := _mock.Called(ctx, GGOrderInfos)

	if len(ret) == 0 {
		panic("no return value specified for InsertGGOrderInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.GGOrderInfo) error); ok {
		r0 = returnFunc(ctx, GGOrderInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGGOrderStorage_InsertGGOrderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertGGOrderInfo'
type MockGGOrderStorage_InsertGGOrderInfo_Call struct {
	*mock.Call
}

// InsertGGOrderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - GGOrderInfos []*models.GGOrderInfo
func (_e *MockGGOrderStorage_Expecter) InsertGGOrderInfo(ctx interface{}, GGOrderInfos interface{}) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	return &MockGGOrderStorage_InsertGGOrderInfo_Call{Call: _e.mock.On("InsertGGOrderInfo", ctx, GGOrderInfos)}
}

func (_c *MockGGOrderStorage_InsertGGOrderInfo_Call) Run(run func(ctx context.Context, GGOrderInfos []*models.GGOrderInfo)) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.GGOrderInfo
		if args[1] != nil {
			arg1 = args[1].([]*models.GGOrderInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGGOrderStorage_InsertGGOrderInfo_Call) Return(err error) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGGOrderStorage_InsertGGOrderInfo_Call) RunAndReturn(run func(ctx context.Context, GGOrderInfos []*models.GGOrderInfo) error) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	_c.Call.Return(run)
	return _c
}
