// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/timur-chilli/ggshop/customer_side/internal/models"
)

// NewMockGGOrderStorage creates a new instance of MockGGOrderStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGGOrderStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGGOrderStorage {
	mock := &MockGGOrderStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGGOrderStorage is an autogenerated mock type for the GGOrderStorage type
type MockGGOrderStorage struct {
	mock.Mock
}

type MockGGOrderStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGGOrderStorage) EXPECT() *MockGGOrderStorage_Expecter {
	return &MockGGOrderStorage_Expecter{mock: &_m.Mock}
}

// GetGGOrderInfoByIDs provides a mock function for the type MockGGOrderStorage
func (_mock *MockGGOrderStorage) GetGGOrderInfoByIDs(ctx context.Context, IDs []uint64) ([]*models.GGOrderInfo, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetGGOrderInfoByIDs")
	}

	var r0 []*models.GGOrderInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.GGOrderInfo, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint64) []*models.GGOrderInfo); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GGOrderInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGGOrderStorage_GetGGOrderInfoByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGGOrderInfoByIDs'
type MockGGOrderStorage_GetGGOrderInfoByIDs_Call struct {
	*mock.Call
}

// GetGGOrderInfoByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockGGOrderStorage_Expecter) GetGGOrderInfoByIDs(ctx interface{}, IDs interface{}) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	return &MockGGOrderStorage_GetGGOrderInfoByIDs_Call{Call: _e.mock.On("GetGGOrderInfoByIDs", ctx, IDs)}
}

func (_c *MockGGOrderStorage_GetGGOrderInfoByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint64
		if args[1] != nil {
			arg1 = args[1].([]uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGGOrderStorage_GetGGOrderInfoByIDs_Call) Return(gGOrderInfos []*models.GGOrderInfo, err error) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	_c.Call.Return(gGOrderInfos, err)
	return _c
}

func (_c *MockGGOrderStorage_GetGGOrderInfoByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uint64) ([]*models.GGOrderInfo, error)) *MockGGOrderStorage_GetGGOrderInfoByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertGGOrderInfo provides a mock function for the type MockGGOrderStorage
func (_mock *MockGGOrderStorage) InsertGGOrderInfo(ctx context.Context, GGOrderInfos []*models.GGOrderInfo) error {
	ret := _mock.Called(ctx, GGOrderInfos)

	if len(ret) == 0 {
		panic("no return value specified for InsertGGOrderInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.GGOrderInfo) error); ok {
		r0 = returnFunc(ctx, GGOrderInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGGOrderStorage_InsertGGOrderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertGGOrderInfo'
type MockGGOrderStorage_InsertGGOrderInfo_Call struct {
	*mock.Call
}

// InsertGGOrderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - GGOrderInfos []*models.GGOrderInfo
func (_e *MockGGOrderStorage_Expecter) InsertGGOrderInfo(ctx interface{}, GGOrderInfos interface{}) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	return &MockGGOrderStorage_InsertGGOrderInfo_Call{Call: _e.mock.On("InsertGGOrderInfo", ctx, GGOrderInfos)}
}

func (_c *MockGGOrderStorage_InsertGGOrderInfo_Call) Run(run func(ctx context.Context, GGOrderInfos []*models.GGOrderInfo)) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.GGOrderInfo
		if args[1] != nil {
			arg1 = args[1].([]*models.GGOrderInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGGOrderStorage_InsertGGOrderInfo_Call) Return(err error) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGGOrderStorage_InsertGGOrderInfo_Call) RunAndReturn(run func(ctx context.Context, GGOrderInfos []*models.GGOrderInfo) error) *MockGGOrderStorage_InsertGGOrderInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGGOrderInfo provides a mock function for the type MockGGOrderStorage
func (_mock *MockGGOrderStorage) UpdateGGOrderInfo(ctx context.Context, originalInfos []*models.GGOrderInfo) error {
	ret := _mock.Called(ctx, originalInfos)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGGOrderInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.GGOrderInfo) error); ok {
		r0 = returnFunc(ctx, originalInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGGOrderStorage_UpdateGGOrderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGGOrderInfo'
type MockGGOrderStorage_UpdateGGOrderInfo_Call struct {
	*mock.Call
}

// UpdateGGOrderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - originalInfos []*models.GGOrderInfo
func (_e *MockGGOrderStorage_Expecter) UpdateGGOrderInfo(ctx interface{}, originalInfos interface{}) *MockGGOrderStorage_UpdateGGOrderInfo_Call {
	return &MockGGOrderStorage_UpdateGGOrderInfo_Call{Call: _e.mock.On("UpdateGGOrderInfo", ctx, originalInfos)}
}

func (_c *MockGGOrderStorage_UpdateGGOrderInfo_Call) Run(run func(ctx context.Context, originalInfos []*models.GGOrderInfo)) *MockGGOrderStorage_UpdateGGOrderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.GGOrderInfo
		if args[1] != nil {
			arg1 = args[1].([]*models.GGOrderInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGGOrderStorage_UpdateGGOrderInfo_Call) Return(err error) *MockGGOrderStorage_UpdateGGOrderInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGGOrderStorage_UpdateGGOrderInfo_Call) RunAndReturn(run func(ctx context.Context, originalInfos []*models.GGOrderInfo) error) *MockGGOrderStorage_UpdateGGOrderInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerCreateOrderProducer creates a new instance of MockCustomerCreateOrderProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerCreateOrderProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerCreateOrderProducer {
	mock := &MockCustomerCreateOrderProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerCreateOrderProducer is an autogenerated mock type for the CustomerCreateOrderProducer type
type MockCustomerCreateOrderProducer struct {
	mock.Mock
}

type MockCustomerCreateOrderProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerCreateOrderProducer) EXPECT() *MockCustomerCreateOrderProducer_Expecter {
	return &MockCustomerCreateOrderProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCustomerCreateOrderProducer
func (_mock *MockCustomerCreateOrderProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerCreateOrderProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCustomerCreateOrderProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCustomerCreateOrderProducer_Expecter) Close() *MockCustomerCreateOrderProducer_Close_Call {
	return &MockCustomerCreateOrderProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCustomerCreateOrderProducer_Close_Call) Run(run func()) *MockCustomerCreateOrderProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCustomerCreateOrderProducer_Close_Call) Return(err error) *MockCustomerCreateOrderProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerCreateOrderProducer_Close_Call) RunAndReturn(run func() error) *MockCustomerCreateOrderProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockCustomerCreateOrderProducer
func (_mock *MockCustomerCreateOrderProducer) Send(ctx context.Context, ggorderInfos []*models.GGOrderInfo) error {
	ret := _mock.Called(ctx, ggorderInfos)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.GGOrderInfo) error); ok {
		r0 = returnFunc(ctx, ggorderInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerCreateOrderProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockCustomerCreateOrderProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - ggorderInfos []*models.GGOrderInfo
func (_e *MockCustomerCreateOrderProducer_Expecter) Send(ctx interface{}, ggorderInfos interface{}) *MockCustomerCreateOrderProducer_Send_Call {
	return &MockCustomerCreateOrderProducer_Send_Call{Call: _e.mock.On("Send", ctx, ggorderInfos)}
}

func (_c *MockCustomerCreateOrderProducer_Send_Call) Run(run func(ctx context.Context, ggorderInfos []*models.GGOrderInfo)) *MockCustomerCreateOrderProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.GGOrderInfo
		if args[1] != nil {
			arg1 = args[1].([]*models.GGOrderInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerCreateOrderProducer_Send_Call) Return(err error) *MockCustomerCreateOrderProducer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerCreateOrderProducer_Send_Call) RunAndReturn(run func(ctx context.Context, ggorderInfos []*models.GGOrderInfo) error) *MockCustomerCreateOrderProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerGetOrderProducer creates a new instance of MockCustomerGetOrderProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerGetOrderProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerGetOrderProducer {
	mock := &MockCustomerGetOrderProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerGetOrderProducer is an autogenerated mock type for the CustomerGetOrderProducer type
type MockCustomerGetOrderProducer struct {
	mock.Mock
}

type MockCustomerGetOrderProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerGetOrderProducer) EXPECT() *MockCustomerGetOrderProducer_Expecter {
	return &MockCustomerGetOrderProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCustomerGetOrderProducer
func (_mock *MockCustomerGetOrderProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerGetOrderProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCustomerGetOrderProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCustomerGetOrderProducer_Expecter) Close() *MockCustomerGetOrderProducer_Close_Call {
	return &MockCustomerGetOrderProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCustomerGetOrderProducer_Close_Call) Run(run func()) *MockCustomerGetOrderProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCustomerGetOrderProducer_Close_Call) Return(err error) *MockCustomerGetOrderProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerGetOrderProducer_Close_Call) RunAndReturn(run func() error) *MockCustomerGetOrderProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockCustomerGetOrderProducer
func (_mock *MockCustomerGetOrderProducer) Send(ctx context.Context, ggorderInfos []*models.GGOrderInfo) error {
	ret := _mock.Called(ctx, ggorderInfos)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.GGOrderInfo) error); ok {
		r0 = returnFunc(ctx, ggorderInfos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerGetOrderProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockCustomerGetOrderProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - ggorderInfos []*models.GGOrderInfo
func (_e *MockCustomerGetOrderProducer_Expecter) Send(ctx interface{}, ggorderInfos interface{}) *MockCustomerGetOrderProducer_Send_Call {
	return &MockCustomerGetOrderProducer_Send_Call{Call: _e.mock.On("Send", ctx, ggorderInfos)}
}

func (_c *MockCustomerGetOrderProducer_Send_Call) Run(run func(ctx context.Context, ggorderInfos []*models.GGOrderInfo)) *MockCustomerGetOrderProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.GGOrderInfo
		if args[1] != nil {
			arg1 = args[1].([]*models.GGOrderInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerGetOrderProducer_Send_Call) Return(err error) *MockCustomerGetOrderProducer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerGetOrderProducer_Send_Call) RunAndReturn(run func(ctx context.Context, ggorderInfos []*models.GGOrderInfo) error) *MockCustomerGetOrderProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}
