// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: warehouse_api/warehouse.proto

package warehouse_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarehouseService_GetGGOrderInfoByIDs_FullMethodName = "/warehouse.service.v1.WarehouseService/GetGGOrderInfoByIDs"
	WarehouseService_UpdateGGOrderInfos_FullMethodName  = "/warehouse.service.v1.WarehouseService/UpdateGGOrderInfos"
)

// WarehouseServiceClient is the client API for WarehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseServiceClient interface {
	GetGGOrderInfoByIDs(ctx context.Context, in *GetGGOrderInfoByIDsRequest, opts ...grpc.CallOption) (*GetGGOrderInfoByIDsResponse, error)
	UpdateGGOrderInfos(ctx context.Context, in *GGOrderInfoUpdateRequest, opts ...grpc.CallOption) (*GGOrderInfoUpdateResponse, error)
}

type warehouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseServiceClient(cc grpc.ClientConnInterface) WarehouseServiceClient {
	return &warehouseServiceClient{cc}
}

func (c *warehouseServiceClient) GetGGOrderInfoByIDs(ctx context.Context, in *GetGGOrderInfoByIDsRequest, opts ...grpc.CallOption) (*GetGGOrderInfoByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGGOrderInfoByIDsResponse)
	err := c.cc.Invoke(ctx, WarehouseService_GetGGOrderInfoByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) UpdateGGOrderInfos(ctx context.Context, in *GGOrderInfoUpdateRequest, opts ...grpc.CallOption) (*GGOrderInfoUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GGOrderInfoUpdateResponse)
	err := c.cc.Invoke(ctx, WarehouseService_UpdateGGOrderInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseServiceServer is the server API for WarehouseService service.
// All implementations must embed UnimplementedWarehouseServiceServer
// for forward compatibility.
type WarehouseServiceServer interface {
	GetGGOrderInfoByIDs(context.Context, *GetGGOrderInfoByIDsRequest) (*GetGGOrderInfoByIDsResponse, error)
	UpdateGGOrderInfos(context.Context, *GGOrderInfoUpdateRequest) (*GGOrderInfoUpdateResponse, error)
	mustEmbedUnimplementedWarehouseServiceServer()
}

// UnimplementedWarehouseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarehouseServiceServer struct{}

func (UnimplementedWarehouseServiceServer) GetGGOrderInfoByIDs(context.Context, *GetGGOrderInfoByIDsRequest) (*GetGGOrderInfoByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGGOrderInfoByIDs not implemented")
}
func (UnimplementedWarehouseServiceServer) UpdateGGOrderInfos(context.Context, *GGOrderInfoUpdateRequest) (*GGOrderInfoUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGGOrderInfos not implemented")
}
func (UnimplementedWarehouseServiceServer) mustEmbedUnimplementedWarehouseServiceServer() {}
func (UnimplementedWarehouseServiceServer) testEmbeddedByValue()                          {}

// UnsafeWarehouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseServiceServer will
// result in compilation errors.
type UnsafeWarehouseServiceServer interface {
	mustEmbedUnimplementedWarehouseServiceServer()
}

func RegisterWarehouseServiceServer(s grpc.ServiceRegistrar, srv WarehouseServiceServer) {
	// If the following call panics, it indicates UnimplementedWarehouseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarehouseService_ServiceDesc, srv)
}

func _WarehouseService_GetGGOrderInfoByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGGOrderInfoByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetGGOrderInfoByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetGGOrderInfoByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetGGOrderInfoByIDs(ctx, req.(*GetGGOrderInfoByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_UpdateGGOrderInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GGOrderInfoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).UpdateGGOrderInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_UpdateGGOrderInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).UpdateGGOrderInfos(ctx, req.(*GGOrderInfoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseService_ServiceDesc is the grpc.ServiceDesc for WarehouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.service.v1.WarehouseService",
	HandlerType: (*WarehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGGOrderInfoByIDs",
			Handler:    _WarehouseService_GetGGOrderInfoByIDs_Handler,
		},
		{
			MethodName: "UpdateGGOrderInfos",
			Handler:    _WarehouseService_UpdateGGOrderInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warehouse_api/warehouse.proto",
}
