// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: customer_side_api/customer_side.proto

package customer_side_api

import (
	models "github.com/timur-chilli/ggshop/customer_side/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGGOrderInfoByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGGOrderInfoByIDsRequest) Reset() {
	*x = GetGGOrderInfoByIDsRequest{}
	mi := &file_customer_side_api_customer_side_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGGOrderInfoByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGGOrderInfoByIDsRequest) ProtoMessage() {}

func (x *GetGGOrderInfoByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_side_api_customer_side_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGGOrderInfoByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetGGOrderInfoByIDsRequest) Descriptor() ([]byte, []int) {
	return file_customer_side_api_customer_side_proto_rawDescGZIP(), []int{0}
}

func (x *GetGGOrderInfoByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetGGOrderInfoByIDsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	GGOrderInfos  []*models.GGOrderInfoModel `protobuf:"bytes,1,rep,name=GGOrderInfos,proto3" json:"GGOrderInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGGOrderInfoByIDsResponse) Reset() {
	*x = GetGGOrderInfoByIDsResponse{}
	mi := &file_customer_side_api_customer_side_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGGOrderInfoByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGGOrderInfoByIDsResponse) ProtoMessage() {}

func (x *GetGGOrderInfoByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_side_api_customer_side_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGGOrderInfoByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetGGOrderInfoByIDsResponse) Descriptor() ([]byte, []int) {
	return file_customer_side_api_customer_side_proto_rawDescGZIP(), []int{1}
}

func (x *GetGGOrderInfoByIDsResponse) GetGGOrderInfos() []*models.GGOrderInfoModel {
	if x != nil {
		return x.GGOrderInfos
	}
	return nil
}

type GetGGOrderInfoInsertRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	GGOrders      []*models.GGOrderInsertModel `protobuf:"bytes,1,rep,name=GGOrders,proto3" json:"GGOrders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGGOrderInfoInsertRequest) Reset() {
	*x = GetGGOrderInfoInsertRequest{}
	mi := &file_customer_side_api_customer_side_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGGOrderInfoInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGGOrderInfoInsertRequest) ProtoMessage() {}

func (x *GetGGOrderInfoInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_side_api_customer_side_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGGOrderInfoInsertRequest.ProtoReflect.Descriptor instead.
func (*GetGGOrderInfoInsertRequest) Descriptor() ([]byte, []int) {
	return file_customer_side_api_customer_side_proto_rawDescGZIP(), []int{2}
}

func (x *GetGGOrderInfoInsertRequest) GetGGOrders() []*models.GGOrderInsertModel {
	if x != nil {
		return x.GGOrders
	}
	return nil
}

type GetGGOrderInfoInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGGOrderInfoInsertResponse) Reset() {
	*x = GetGGOrderInfoInsertResponse{}
	mi := &file_customer_side_api_customer_side_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGGOrderInfoInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGGOrderInfoInsertResponse) ProtoMessage() {}

func (x *GetGGOrderInfoInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_side_api_customer_side_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGGOrderInfoInsertResponse.ProtoReflect.Descriptor instead.
func (*GetGGOrderInfoInsertResponse) Descriptor() ([]byte, []int) {
	return file_customer_side_api_customer_side_proto_rawDescGZIP(), []int{3}
}

var File_customer_side_api_customer_side_proto protoreflect.FileDescriptor

const file_customer_side_api_customer_side_proto_rawDesc = "" +
	"\n" +
	"%customer_side_api/customer_side.proto\x12\x18customer_side.service.v1\x1a\x1amodels/ggorder_model.proto\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x1aGetGGOrderInfoByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"f\n" +
	"\x1bGetGGOrderInfoByIDsResponse\x12G\n" +
	"\fGGOrderInfos\x18\x01 \x03(\v2#.ggorder.models.v1.GGOrderInfoModelR\fGGOrderInfos\"`\n" +
	"\x1bGetGGOrderInfoInsertRequest\x12A\n" +
	"\bGGOrders\x18\x01 \x03(\v2%.ggorder.models.v1.GGOrderInsertModelR\bGGOrders\"\x1e\n" +
	"\x1cGetGGOrderInfoInsertResponse2\xe4\x02\n" +
	"\x13CustomerSideService\x12\xa6\x01\n" +
	"\x13GetGGOrderInfoByIDs\x124.customer_side.service.v1.GetGGOrderInfoByIDsRequest\x1a5.customer_side.service.v1.GetGGOrderInfoByIDsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/ggorderInfo/get-by-ids\x12\xa3\x01\n" +
	"\x12InsertGGOrderInfos\x125.customer_side.service.v1.GetGGOrderInfoInsertRequest\x1a6.customer_side.service.v1.GetGGOrderInfoInsertResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/ggorderInfo/insertBLZJgithub.com/timur-chilli/ggshop/customer_side/internal/pb/customer_side_apib\x06proto3"

var (
	file_customer_side_api_customer_side_proto_rawDescOnce sync.Once
	file_customer_side_api_customer_side_proto_rawDescData []byte
)

func file_customer_side_api_customer_side_proto_rawDescGZIP() []byte {
	file_customer_side_api_customer_side_proto_rawDescOnce.Do(func() {
		file_customer_side_api_customer_side_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_side_api_customer_side_proto_rawDesc), len(file_customer_side_api_customer_side_proto_rawDesc)))
	})
	return file_customer_side_api_customer_side_proto_rawDescData
}

var file_customer_side_api_customer_side_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_customer_side_api_customer_side_proto_goTypes = []any{
	(*GetGGOrderInfoByIDsRequest)(nil),   // 0: customer_side.service.v1.GetGGOrderInfoByIDsRequest
	(*GetGGOrderInfoByIDsResponse)(nil),  // 1: customer_side.service.v1.GetGGOrderInfoByIDsResponse
	(*GetGGOrderInfoInsertRequest)(nil),  // 2: customer_side.service.v1.GetGGOrderInfoInsertRequest
	(*GetGGOrderInfoInsertResponse)(nil), // 3: customer_side.service.v1.GetGGOrderInfoInsertResponse
	(*models.GGOrderInfoModel)(nil),      // 4: ggorder.models.v1.GGOrderInfoModel
	(*models.GGOrderInsertModel)(nil),    // 5: ggorder.models.v1.GGOrderInsertModel
}
var file_customer_side_api_customer_side_proto_depIdxs = []int32{
	4, // 0: customer_side.service.v1.GetGGOrderInfoByIDsResponse.GGOrderInfos:type_name -> ggorder.models.v1.GGOrderInfoModel
	5, // 1: customer_side.service.v1.GetGGOrderInfoInsertRequest.GGOrders:type_name -> ggorder.models.v1.GGOrderInsertModel
	0, // 2: customer_side.service.v1.CustomerSideService.GetGGOrderInfoByIDs:input_type -> customer_side.service.v1.GetGGOrderInfoByIDsRequest
	2, // 3: customer_side.service.v1.CustomerSideService.InsertGGOrderInfos:input_type -> customer_side.service.v1.GetGGOrderInfoInsertRequest
	1, // 4: customer_side.service.v1.CustomerSideService.GetGGOrderInfoByIDs:output_type -> customer_side.service.v1.GetGGOrderInfoByIDsResponse
	3, // 5: customer_side.service.v1.CustomerSideService.InsertGGOrderInfos:output_type -> customer_side.service.v1.GetGGOrderInfoInsertResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_customer_side_api_customer_side_proto_init() }
func file_customer_side_api_customer_side_proto_init() {
	if File_customer_side_api_customer_side_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_side_api_customer_side_proto_rawDesc), len(file_customer_side_api_customer_side_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_side_api_customer_side_proto_goTypes,
		DependencyIndexes: file_customer_side_api_customer_side_proto_depIdxs,
		MessageInfos:      file_customer_side_api_customer_side_proto_msgTypes,
	}.Build()
	File_customer_side_api_customer_side_proto = out.File
	file_customer_side_api_customer_side_proto_goTypes = nil
	file_customer_side_api_customer_side_proto_depIdxs = nil
}
