// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: customer_side_api/customer_side.proto

package customer_side_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerSideService_GetGGOrderInfoByIDs_FullMethodName = "/customer_side.service.v1.CustomerSideService/GetGGOrderInfoByIDs"
	CustomerSideService_InsertGGOrderInfos_FullMethodName  = "/customer_side.service.v1.CustomerSideService/InsertGGOrderInfos"
)

// CustomerSideServiceClient is the client API for CustomerSideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerSideServiceClient interface {
	GetGGOrderInfoByIDs(ctx context.Context, in *GetGGOrderInfoByIDsRequest, opts ...grpc.CallOption) (*GetGGOrderInfoByIDsResponse, error)
	InsertGGOrderInfos(ctx context.Context, in *GetGGOrderInfoInsertRequest, opts ...grpc.CallOption) (*GetGGOrderInfoInsertResponse, error)
}

type customerSideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerSideServiceClient(cc grpc.ClientConnInterface) CustomerSideServiceClient {
	return &customerSideServiceClient{cc}
}

func (c *customerSideServiceClient) GetGGOrderInfoByIDs(ctx context.Context, in *GetGGOrderInfoByIDsRequest, opts ...grpc.CallOption) (*GetGGOrderInfoByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGGOrderInfoByIDsResponse)
	err := c.cc.Invoke(ctx, CustomerSideService_GetGGOrderInfoByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerSideServiceClient) InsertGGOrderInfos(ctx context.Context, in *GetGGOrderInfoInsertRequest, opts ...grpc.CallOption) (*GetGGOrderInfoInsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGGOrderInfoInsertResponse)
	err := c.cc.Invoke(ctx, CustomerSideService_InsertGGOrderInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerSideServiceServer is the server API for CustomerSideService service.
// All implementations must embed UnimplementedCustomerSideServiceServer
// for forward compatibility.
type CustomerSideServiceServer interface {
	GetGGOrderInfoByIDs(context.Context, *GetGGOrderInfoByIDsRequest) (*GetGGOrderInfoByIDsResponse, error)
	InsertGGOrderInfos(context.Context, *GetGGOrderInfoInsertRequest) (*GetGGOrderInfoInsertResponse, error)
	mustEmbedUnimplementedCustomerSideServiceServer()
}

// UnimplementedCustomerSideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerSideServiceServer struct{}

func (UnimplementedCustomerSideServiceServer) GetGGOrderInfoByIDs(context.Context, *GetGGOrderInfoByIDsRequest) (*GetGGOrderInfoByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGGOrderInfoByIDs not implemented")
}
func (UnimplementedCustomerSideServiceServer) InsertGGOrderInfos(context.Context, *GetGGOrderInfoInsertRequest) (*GetGGOrderInfoInsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertGGOrderInfos not implemented")
}
func (UnimplementedCustomerSideServiceServer) mustEmbedUnimplementedCustomerSideServiceServer() {}
func (UnimplementedCustomerSideServiceServer) testEmbeddedByValue()                             {}

// UnsafeCustomerSideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerSideServiceServer will
// result in compilation errors.
type UnsafeCustomerSideServiceServer interface {
	mustEmbedUnimplementedCustomerSideServiceServer()
}

func RegisterCustomerSideServiceServer(s grpc.ServiceRegistrar, srv CustomerSideServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomerSideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerSideService_ServiceDesc, srv)
}

func _CustomerSideService_GetGGOrderInfoByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGGOrderInfoByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerSideServiceServer).GetGGOrderInfoByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerSideService_GetGGOrderInfoByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerSideServiceServer).GetGGOrderInfoByIDs(ctx, req.(*GetGGOrderInfoByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerSideService_InsertGGOrderInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGGOrderInfoInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerSideServiceServer).InsertGGOrderInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerSideService_InsertGGOrderInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerSideServiceServer).InsertGGOrderInfos(ctx, req.(*GetGGOrderInfoInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerSideService_ServiceDesc is the grpc.ServiceDesc for CustomerSideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerSideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer_side.service.v1.CustomerSideService",
	HandlerType: (*CustomerSideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGGOrderInfoByIDs",
			Handler:    _CustomerSideService_GetGGOrderInfoByIDs_Handler,
		},
		{
			MethodName: "InsertGGOrderInfos",
			Handler:    _CustomerSideService_InsertGGOrderInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer_side_api/customer_side.proto",
}
